tap "filippo.io/age", "https://filippo.io/age"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
brew "age"
brew "aria2"
brew "bat"
brew "coreutils"
brew "croc"
brew "ctags"
brew "curlie"
brew "direnv"
brew "docker"
brew "dust"
brew "duti"
brew "editorconfig"
brew "exa"
brew "exiftool"
brew "fasd", args: ["HEAD"]
brew "fd"
brew "frpc"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow-avh"
brew "git-lfs"
brew "gitui"
brew "gnu-sed"
brew "gnupg"
brew "gopass"
brew "grep"
brew "hugo"
brew "imageoptim-cli"
brew "ipython"
brew "jq"
brew "mas"
brew "mdbook"
brew "mosh"
brew "neovim"
brew "oath-toolkit"
brew "p7zip"
brew "pandoc"
brew "pidof"
brew "pinentry-mac"
brew "pyright"
brew "ripgrep"
brew "rlwrap"
brew "rsync"
brew "rust-analyzer"
brew "shfmt"
brew "smartmontools"
brew "socat"
brew "starship"
brew "subversion"
brew "tag"
brew "tailscale"
brew "tarsnap"
brew "telnet"
brew "tmux"
brew "trash"
brew "unar"
brew "watchexec"
brew "wget"
brew "youtube-dl"
cask "a-better-finder-rename"
cask "aegisub"
cask "anki"
cask "app-cleaner"
cask "app-tamer"
cask "audacity"
cask "audio-hijack"
cask "brave-browser"
cask "calibre"
cask "carbon-copy-cloner"
cask "cardhop"
cask "cleanshot"
cask "deckset"
cask "deepl"
cask "dropbox"
cask "fantastical"
cask "fission"
cask "font-lato"
cask "font-montserrat-alternates"
cask "font-noto-sans"
cask "font-noto-sans-cjk-sc"
cask "font-noto-serif"
cask "font-noto-serif-cjk-sc"
cask "garmin-express"
cask "google-chrome"
cask "handbrake"
cask "hook"
cask "iina"
cask "imageoptim"
cask "keyboard-maestro"
cask "macvim"
cask "marginnote"
cask "mathpix-snipping-tool"
cask "medibangpaintpro"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-remote-desktop"
cask "microsoft-word"
cask "obs"
cask "obsidian"
cask "omnigraffle"
cask "oracle-jdk"
cask "paragon-ntfs"
cask "paw"
cask "pdf-expert"
cask "prowritingaid"
cask "resilio-sync"
cask "scrivener"
cask "tableflip"
cask "transmission"
cask "uhk-agent"
cask "upic"
cask "vb-cable"
cask "visual-studio-code"
cask "wacom-inkspace"
cask "wacom-tablet"
cask "wechat"
cask "yt-music"
cask "yubico-authenticator"
cask "yubico-yubikey-manager"
cask "zotero"
mas "Amphetamine", id: 937984704
mas "ArtRage Vitae", id: 1532816883
mas "Cardflow", id: 1439830689
mas "Contacts Sync for Google Gmail", id: 451691288
mas "Day One", id: 1055511498
mas "Eagle for Safari", id: 1526651672
mas "Final Cut Pro", id: 424389933
mas "Gestimer", id: 990588172
mas "GoodNotes", id: 1444383602
mas "HazeOver", id: 430798174
mas "Hex Fiend", id: 1342896380
mas "Hidden Bar", id: 1452453066
mas "iA Writer", id: 775737590
mas "Kindle", id: 405399194
mas "LiquidText", id: 922765270
mas "Mischief", id: 928430260
mas "Motion", id: 434290957
mas "Notability", id: 360593530
mas "Numbers", id: 409203825
mas "Pixelmator Pro", id: 1289583905
mas "QQ音乐", id: 595615424
mas "ScanScan", id: 1249901692
mas "Tiny Softbox", id: 1599476381
mas "Vimeo", id: 1356686763
mas "Wakeout", id: 1242116567
mas "Xee³", id: 639764244
mas "Yoink", id: 457622435
